### ISSUE TITLE
Process.query attempts to get database credentials from agent, needs to use broker

### ISSUE THREAD

**Issue by treilly-nuodb** [nuodb/nuodb-python#130]
Traceback (most recent call last):
  File "/home/treilly/nuodb/DebugTools/memprof.py", line 32, in <module>
    str = p.query("Memory", ElementTree.fromstring("<Memory Verbose='true' Profile='true'/>"))
  File "/usr/local/lib/python2.7/dist-packages/pynuodb/entity.py", line 951, in query
    "Database" : self.database.name })
  File "/usr/local/lib/python2.7/dist-packages/pynuodb/session.py", line 149, in doRequest
    checkForError(response)
  File "/usr/local/lib/python2.7/dist-packages/pynuodb/session.py", line 56, in checkForError
    raise SessionException(root.get("text"))
pynuodb.session.SessionException: 'Unknown management type: GetDatabaseCredentials'

**Comment by treilly-nuodb** [comment]
Fix: a3bfa2427fa66e697c2f43a822dcd4c44f6c79aa
