### ISSUE TITLE
Entity database shutdown error on windows

### ISSUE THREAD

**Issue by jgetto** [nuodb/nuodb-python#19]
Shutting down a database on windows causes the follow error:

Traceback (most recent call last):
  File "tests/nuodb_entity_test.py", line 27, in setUp
    self._cleanup(domain)
  File "tests/nuodb_entity_test.py", line 338, in _cleanup
    db.shutdown()
  File "c:\Python27\lib\site-packages\pynuodb\entity.py", line 467, in shutdown
    self.quiesce()
  File "c:\Python27\lib\site-packages\pynuodb\entity.py", line 502, in quiesce
    self.__name, DatabaseAction.Quiesce)
  File "c:\Python27\lib\site-packages\pynuodb\util.py", line 106, in doDatabaseA
ction
    checkForError(response)
  File "c:\Python27\lib\site-packages\pynuodb\session.py", line 56, in checkForE
rror
    raise SessionException(root.get("text"))
SessionException: 'WIN-LCFGI29L425.localdomain'

**Comment by madscientist** [comment]
The entity management aspect of the nuodb-python driver is no longer valid, since support for NuoDB Agent was deprecated in 4.0.  Please use the pynuoadmin module to manage databases that run with NuoDB Admin, not nuodb-python.
