### ISSUE TITLE
Python tests fail against current master

### ISSUE THREAD

**Issue by philip-stoev** [nuodb/nuodb-python#20]
```
python run_tests.py
...........F.......F...................................................
======================================================================
FAIL: test_param_date_types (tests.nuodb_basic_test.NuoDBBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philips/git/nuodb-python/tests/nuodb_basic_test.py", line 465, in test_param_date_types
    self.assertEqual(row[2].hour, test_vals[1].hour)
AssertionError: 10 != 0

======================================================================
FAIL: test_string_into_number (tests.nuodb_basic_test.NuoDBBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philips/git/nuodb-python/tests/nuodb_basic_test.py", line 287, in test_string_into_number
    self.assertEqual(row[0], decimal.Decimal(test_vals[0]))
AssertionError: '54.4978' != Decimal('54.4978')

----------------------------------------------------------------------
Ran 71 tests in 13.016s
```

**Comment by tvincentNuoDB** [comment]
These tests have been passed by the latest version of the driver, as shown in the Travis CI build [here](https://travis-ci.org/nuodb/nuodb-python/jobs/64579544)
