### ISSUE TITLE
pynuodb "select *" on system table fails with 'Not a UUID' on numeric(20)

### ISSUE THREAD

**Issue by rjwirth** [nuodb/nuodb-python#25]
```
from pynuodb import connect
db = connect('test', 'localhost', 'dba', 'dba')
c = db.cursor()
c.execute('select * from system.connections')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynuodb/cursor.py", line 142, in execute
    row[i] = self.session.getValue()
  File "/Library/Python/2.7/site-packages/pynuodb/encodedsession.py", line 443, in getValue
    return self.getUUID()
  File "/Library/Python/2.7/site-packages/pynuodb/encodedsession.py", line 425, in getUUID
    raise DataError('Not a UUID')
pynuodb.exception.DataError: 'Not a UUID'
```

To work around this, skip the "EXECID" column.

```
SQL> show system.connections;
 
    Tables named CONNECTIONS

    Found table CONNECTIONS in schema SYSTEM

        Fields:
            SQLSTRING string
            COUNT integer
            RUNTIME bigint
            USER string
            SCHEMA string
            NUMPARAM integer
            PARAMS string
            CONNID integer
            OPEN integer
            HANDLE integer
            NODEID integer
            EXECID numeric(20)
```

**Comment by tvincentNuoDB** [comment]
I was able to fix this by removing ScaledCount2 from UUID. Pushing changes soon

**Comment by rbuck** [comment]
Nice!
