### ISSUE TITLE
DataError: 'INVALID_UTF8: invalid UTF-8 code sequence' when inserting Decimal values with many significant digits

### ISSUE THREAD

**Issue by jgetto** [nuodb/nuodb-python#65]
When inserting the value decimal.Decimal("31943874831932418390.01") into a numeric column, the database responds with the error 'INVALID_UTF8: invalid UTF-8 code sequence'

This could be an encoding error on the send side of the driver, or an error in the database itself.

```
Traceback (most recent call last):
  File "/home/travis/build/nuodb/nuodb-python/tests/nuodb_basic_test.py", line 160, in test_many_significant_digits
    self._test_decimal_fixture(decimal.Decimal("31943874831932418390.01"), 38, 12)
  File "/home/travis/build/nuodb/nuodb-python/tests/nuodb_basic_test.py", line 139, in _test_decimal_fixture
    cursor.execute("INSERT INTO t (x) VALUES (?)", (value,))
  File "/home/travis/build/nuodb/nuodb-python/pynuodb/cursor.py", line 116, in execute
    exec_result = self._executeprepared(operation, parameters)
  File "/home/travis/build/nuodb/nuodb-python/pynuodb/cursor.py", line 142, in _executeprepared
    return self.session.execute_prepared_statement(p_statement, parameters)
  File "/home/travis/build/nuodb/nuodb-python/pynuodb/encodedsession.py", line 217, in execute_prepared_statement
    self._exchangeMessages()
  File "/home/travis/build/nuodb/nuodb-python/pynuodb/encodedsession.py", line 796, in _exchangeMessages
    db_error_handler(error, self.getString())
  File "/home/travis/build/nuodb/nuodb-python/pynuodb/exception.py", line 86, in db_error_handler
    raise DataError(error_code_string + ': ' + error_string)
DataError: 'INVALID_UTF8: invalid UTF-8 code sequence'
```

**Comment by rbuck** [comment]
Tim, this ought to be part of your testing and fixes.
